databases:
  - name: rails_postgres_development
    databaseName: rails_postgres_development
    user: rails_postgres
    plan: free 

services:
  - type: web
    name: mysite
    env: ruby
    plan: free 
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_postgres_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false